Do property substitution using JAXB
ehcache/ehcache3 pull request #2725
Opened 2019-11-22 14:24 UTC by chrisdennis

Lets make a go/no-go decision on this idea.

2020-11-25 20:31 UTC, cljohnso commented
We should probably beef up the documentation to add cautions about safely using properties for certain values that should remain stable for the life of a server.

For the numeric types, I think the schema currently protects against composition of values (permitting either a numeric value or a single property) but internal parsing supports composed values.  I don't think its necessary to change the parsing for this (as long as the schema prevents it) but it may be wise to add a test or two to ensure this isn't changed without proper consideration.

2020-11-25 20:32 UTC, cljohnso requested changes
The only necessary change is the validation for the specific numeric types when the values are supplied by property substitution.

2020-11-25 20:32 UTC, cljohnso commented on xml/src/main/resources/ehcache-core.xsd
> +        <jaxb:javaType name="java.math.BigInteger" parseMethod="org.ehcache.xml.JaxbParsers.parseSubInteger"/>
Should probably have type-specific validation for `propertyReference` values.

2020-11-25 20:32 UTC, cljohnso commented on xml/src/main/resources/ehcache-core.xsd
> +        <jaxb:javaType name="java.math.BigInteger" parseMethod="org.ehcache.xml.JaxbParsers.parseSubInteger"/>
Should probably have type-specific validation for `propertyReference` values.

2020-12-02 18:42 UTC, chrisdennis commented
I still need to make documentation changes... but I think the coding/testing changes are complete.

2020-12-04 21:37 UTC, cljohnso approved these changes

2020-12-04 21:40 UTC, merged