Version upgrades (depends on #3010)
ehcache/ehcache3 pull request #3011
Opened 2022-04-12 11:42 UTC by mathieucarbou

Version upgrades (depends on #3010)

2022-04-12 21:15 UTC, chrisdennis requested changes

2022-04-12 21:15 UTC, chrisdennis commented on ehcache-xml/build.gradle
> +      'Import-Package': "jakarta.xml.bind*;version=\"[3,3.1)\", *"
Should be `[3,4)` since this is exported by the jaxb-api.

2022-04-12 21:15 UTC, chrisdennis commented on ehcache/build.gradle
> +    instruction Constants.IMPORT_PACKAGE, 'javax.cache.*;resolution:=optional, !javax.annotation, !sun.misc, jakarta.xml.bind*;version="[3,3.1)", *'
Should be [3,4) since this is exported by the jaxb-api.

2022-04-13 09:49 UTC, mathieucarbou commented
@chrisdennis : a random test failure: [getCache_Missing_Stopped](https://dev.azure.com/TerracottaCI/ehcache/_build/results?buildId=9180&view=ms.vss-test-web.build-test-results-tab&runId=1131248&resultId=100854&paneView=debug)

2022-04-15 11:35 UTC, mathieucarbou commented
@chrisdennis : merging now to trigger an EE upgrade PR, otherwise this will be stacked with all other new incoming changes which will complicate things.

This upgrade PR is fine and only contains all the angela fixes, platform fixes and test improvements.

2022-04-15 13:07 UTC, chrisdennis approved these changes

2022-04-15 13:07 UTC, merged