Fix issue-2852 : Improve javadoc for getCacheManager() methods in Ehc…
ehcache/ehcache3 pull request #3090
Opened 2022-11-29 16:43 UTC by jitendra-nalwaya

Clarify javadoc for getCacheManager() methods in EhcacheCachingProvider.

2022-12-01 21:34 UTC, chrisdennis requested changes
Rather than attempting to migrate your Javadoc to where I think it needs to be with incremental changes I decided it was easier for all parties to provide the Javadoc as I think it should be. Please review, modify to your tastes, and then push the result. Feel free to ask questions if anything is unclear.

2022-12-05 21:44 UTC, chrisdennis approved these changes

2022-12-05 21:45 UTC, chrisdennis commented
@jhouserizer @AbfrmBlr can one of you guys review this since it's had too much of my hand in it for my review to be independent.

2022-12-07 18:18 UTC, jhouserizer approved these changes

2022-12-07 18:18 UTC, merged