fix for issue2742 null pointer exception
ehcache/ehcache3 pull request #3101
Opened 2022-12-15 14:51 UTC by ajaymaddi31

fix for issue2742 null pointer exception

2022-12-15 15:19 UTC, AbfrmBlr commented
IMHO the way to look into the problem is to understand the tiering model, and contract of flush method in AuthoritativeTier. In addition to the java docs on interfaces you can read about the whole tiering design here https://github.com/ehcache/ehcache3/blob/master/docs/src/docs/asciidoc/developer/design.tiering.adoc.

2022-12-23 13:04 UTC, ajaymaddi31 commented
we are getting valueHolder as null in getOrComputeIfAbsent method because it is unable to fetch the value for the key from cache and in the subsequent call to flush method throwing null pointer exception because of this issue.Now we are handling with this null check.After handling the null check we are not getting null pointer issue even after running the test case for 2 hours.

2023-01-03 14:53 UTC, chrisdennis approved these changes

2023-01-03 14:55 UTC, chrisdennis requested changes
This looks like the correct fix. That said we need to remove the unrelated whitespace changes, and we need to add some test coverage. A unit test for the NoOpCachingTier, and ideally some kind of integration test (maybe using a mocked authoritative tier?) that can reproduce the original issue.

2023-01-06 14:27 UTC, ajaymaddi31 commented
Unit test case for NoopCachingTier(private static class in TieredStore.java) the method(getOrComputeIfAbsent) in NoopCachingTier is covered in TieredStoreTest.java, CachingTierDoesNotSeeAnyOperationDuringClear covers this method in NoopCachingTier.

Unit test case to Reproduce the NullPointerexception:-
we are getting the null pointer exception in flush method in AbstractOffHeapStore.java class. In AbstractOffHeapStoreTest.java class has one test case named testFlushUpdateAccessStats covers flush method, by passing firstValuHolder and secondValueHolder. I wrote a similar test case(testFlushUpdateAccessStatsForNullPointerException) by passing the parameters(firstValueHolder,secondValueHolder) as null to reproduce the NullPointerException.

2023-01-06 16:51 UTC, chrisdennis commented
Yeah, the test here doesn't seem to make sense given the context of the bug and the way the tiered store works. Can you schedule a 30 minute slot some time next week so we can discuss this, and I can explain what's going on with this code, why the null-check is really necessary, and what test needs to be written to reproduce the original NPE, and therefore prove the fix is correct.

2023-01-10 12:49 UTC, ajaymaddi31 commented
As per the yesterday's discussion added test case to cover the  scenario for not calling flush method if the value is null.

2023-01-10 14:15 UTC, chrisdennis requested changes

2023-01-10 14:15 UTC, chrisdennis commented on ehcache-impl/src/test/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStoreTest.java
> +  public void testFlushUpdatesAccessStatsForNullPointerException() throws StoreAccessException {
This test can be removed.

2023-01-10 14:15 UTC, chrisdennis commented on ehcache-impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
> +      //this null check is to handle the null pointer exception that can be thrown from the flush method
Can we phrase this more concretely, and maybe without using a negation. Something like:
```java
if (apply != null) {
  //immediately flush any entries faulted from the authority as this tier has no capacity
  authoritativeTier.flush(key, apply);
}
```

2023-01-10 14:15 UTC, chrisdennis commented on ehcache-impl/src/main/java/org/ehcache/impl/internal/store/offheap/AbstractOffHeapStore.java
> -      boolean result = backingMap().computeIfPinned(key, (k, valuePresent) -> {
These indentation changes should be removed so that the file stays unmodified.

2023-01-12 13:10 UTC, ajaymaddi31 commented
A gentle remainder, Please let us know if there are any review comments?

2023-01-12 14:37 UTC, chrisdennis commented
> A gentle reminder, Please let us know if there are any review comments?

https://user-images.githubusercontent.com/954331/212095088-555f7832-e160-4e4f-ba97-15579ce5ab7e.mov

2023-01-12 14:46 UTC, chrisdennis requested changes

2023-01-12 14:46 UTC, chrisdennis commented on ehcache-impl/src/main/java/org/ehcache/impl/internal/store/tiering/TieredStore.java
> +      Optional<ValueHolder<V>> ap = Optional.ofNullable(apply);
Why the optional? It seems like all this does is create an object for no real benefit?

2023-01-12 14:46 UTC, chrisdennis commented on ehcache-impl/src/test/java/org/ehcache/impl/internal/store/tiering/TieredStoreTest.java
> +    verify(stringAuthoritativeTier,never()).flush("foo",null);
Can you fix the formatting here to confirm to some reasonable standard. A reasonable version could be:
```java
verify(stringAuthoritativeTier, never()).flush("foo", null);
```

2023-01-17 14:36 UTC, chrisdennis requested changes

2023-01-18 18:29 UTC, chrisdennis commented
Before this can be merged the fix will need to be rebased to be a daggy fix against the commit that introduced the bug. I believe that's going to be the commit that introduces the concept of the `NoopCachingTier`. It should probably also be squashed to be a more logical commit stream.

2023-01-20 05:11 UTC, ajaymaddi31 commented
closing this PR.
#3114  is the replacement for this PR 
https://github.com/ehcache/ehcache3/pull/3114

2023-01-20 05:12 UTC, closed without merging