Issue 2742 new
ehcache/ehcache3 pull request #3114
Opened 2023-01-19 09:15 UTC by ajaymaddi31

issue#2742

2023-01-19 15:38 UTC, chrisdennis requested changes
The changes look good... and I think the commit structure is legitimate. The merge commit needs to have a better commit message. It really needs to identify that it is a merge commit, and what it merges in to where, and why. So if you were merging `main` in to the fix branch then it would say that, if you merged the fix branch in to main (aka an integration branch) then it would mention that. Leaving the commit message as is would be confusing for anyone browsing the commit history in the future.

2023-01-19 18:47 UTC, jhouserizer commented
>  Leaving the commit message as is would be confusing for anyone browsing the commit history in the future.

I agree, because funny enough, it took me some effort to figure out what the difference was between the two commits.

2023-01-23 14:05 UTC, chrisdennis requested changes
The changes are good, the commit structure is good, but the commit message on the merge commit is wrong. It doesn't merge f2c76ad85b41009800d736e755498e396e1559f3 into issue-2742 it appears it merges b7ffc81f97157e4294c8bca1e7298c2b6f865a23 in to the branch (or maybe the other way round, hard to tell from the GitHub UI).

2023-01-23 18:51 UTC, chrisdennis approved these changes

2023-01-23 18:51 UTC, merged